package com.kevin.zuyu.model;

import com.kevin.orm.mapping.AutoGenerated;
import com.kevin.orm.mapping.Column;
import com.kevin.orm.mapping.PK_ID;
import com.kevin.orm.mapping.Table;

@Table(name = "bao_jian_shi")
public class BaoJianShi implements java.io.Serializable {
  private static final long serialVersionUID = 390936674717966410L;
  @PK_ID
  @AutoGenerated
  private Integer id;
  @Column(name = "name")
  private String name;
  @Column(name = "status")
  private Integer status;
  @Column(name = "employe_no")
  private String employeNo;

  public String getEmployeNo() {
    return employeNo;
  }

  public void setEmployeNo(String employeNo) {
    this.employeNo = employeNo;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public Integer getStatus() {
    return this.status;
  }

  public BaoJianShi() {}

  public BaoJianShi(Integer id, String name, Integer status) {
    this.id = id;
    this.name = name;
    this.status = status;
  }
}
