package com.kevin.zuyu.model;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;

import com.kevin.orm.mapping.AutoGenerated;
import com.kevin.orm.mapping.Column;
import com.kevin.orm.mapping.PK_ID;
import com.kevin.orm.mapping.Table;

@Table(name = "orders")
public class Order implements java.io.Serializable {
  private static final long serialVersionUID = -2008474056603510352L;
  @PK_ID
  @AutoGenerated
  private Integer id;
  @Column(name = "room_id")
  private Integer roomId;// 房间ID
  @Column(name = "persion_num")
  private Integer persionNum;// 人数
  @Column(name = "enter_time")
  private Timestamp enterTime;// 进入时间
  @Column(name = "total_price")
  private BigDecimal totalPrice;// 总价格
  @Column(name = "jie_zhang")
  private Integer jieZhang;// 是否结账
  @Column(name = "leave_time")
  private Timestamp leaveTime;// 离开时间
  //实际收取金额
  @Column(name="gather_price")
  private BigDecimal gather_price;
  public BigDecimal getGather_price() {
    return gather_price;
  }

  public void setGather_price(BigDecimal gather_price) {
    this.gather_price = gather_price;
  }

  private Room room;
  private List<OrderProduct> products;

  private List<TaocanOrder> taocans;

  private List<ServiceOrder> services;

  public List<ServiceOrder> getServices() {
    return services;
  }

  public void setServices(List<ServiceOrder> services) {
    this.services = services;
  }


  public List<TaocanOrder> getTaocans() {
    return taocans;
  }

  public void setTaocans(List<TaocanOrder> taocans) {
    this.taocans = taocans;
  }

  public List<OrderProduct> getProducts() {
    return products;
  }

  public void setProducts(List<OrderProduct> products) {
    this.products = products;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setRoomId(Integer roomId) {
    this.roomId = roomId;
  }

  public Integer getRoomId() {
    return this.roomId;
  }

  public void setPersionNum(Integer persionNum) {
    this.persionNum = persionNum;
  }

  public Integer getPersionNum() {
    return this.persionNum;
  }

  public Room getRoom() {
    return room;
  }

  public void setRoom(Room room) {
    this.room = room;
  }

  public void setEnterTime(Timestamp enterTime) {
    this.enterTime = enterTime;
  }

  public Timestamp getEnterTime() {
    return this.enterTime;
  }

  public void setTotalPrice(BigDecimal totalPrice) {
    this.totalPrice = totalPrice;
  }

  public BigDecimal getTotalPrice() {
    return this.totalPrice;
  }

  public void setJieZhang(Integer jieZhang) {
    this.jieZhang = jieZhang;
  }

  public Integer getJieZhang() {
    return this.jieZhang;
  }

  public void setLeaveTime(Timestamp leaveTime) {
    this.leaveTime = leaveTime;
  }

  public Timestamp getLeaveTime() {
    return this.leaveTime;
  }

  public Order() {}

}
