package com.kevin.zuyu.model;

import java.math.BigDecimal;
import java.util.Date;

import com.kevin.orm.mapping.AutoGenerated;
import com.kevin.orm.mapping.Column;
import com.kevin.orm.mapping.PK_ID;
import com.kevin.orm.mapping.Table;

@Table(name = "order_product")
public class OrderProduct {
  @PK_ID
  @AutoGenerated
  private int id;
  @Column(name = "order_id")
  private int orderId;
  @Column(name = "product_id")
  private int productId;
  @Column(name = "create_time")
  private Date createTime;
  @Column(name = "num")
  private Integer num;
  @Column(name = "price")
  private BigDecimal price;
  private String productName;

  public String getProductName() {
    return productName;
  }

  public void setProductName(String productName) {
    this.productName = productName;
  }

  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public Integer getNum() {
    return num;
  }

  public void setNum(Integer num) {
    this.num = num;
  }

  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public int getOrderId() {
    return orderId;
  }

  public void setOrderId(int orderId) {
    this.orderId = orderId;
  }

  public int getProductId() {
    return productId;
  }

  public void setProductId(int productId) {
    this.productId = productId;
  }

  public Date getCreateTime() {
    return createTime;
  }

  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }
}
