package com.kevin.zuyu.model;

import java.math.BigDecimal;

import com.kevin.orm.mapping.AutoGenerated;
import com.kevin.orm.mapping.Column;
import com.kevin.orm.mapping.PK_ID;
import com.kevin.orm.mapping.Table;

@Table(name = "product")
public class Product implements java.io.Serializable {
  private static final long serialVersionUID = 6677027362620503642L;
  @PK_ID
  @AutoGenerated
  private Integer id;
  @Column(name = "name")
  private String name;
  @Column(name = "price")
  private BigDecimal price;
  @Column(name = "status")
  private Integer status;

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public BigDecimal getPrice() {
    return this.price;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public Integer getStatus() {
    return this.status;
  }

  public Product() {}

  public Product(Integer id, String name, BigDecimal price, Integer status) {
    this.id = id;
    this.name = name;
    this.price = price;
    this.status = status;
  }
}
