package com.kevin.zuyu.model;

import com.kevin.orm.mapping.AutoGenerated;
import com.kevin.orm.mapping.Column;
import com.kevin.orm.mapping.PK_ID;
import com.kevin.orm.mapping.Table;

@Table(name = "room")
public class Room implements java.io.Serializable {
  private static final long serialVersionUID = -4998860648798698541L;
  @PK_ID
  @AutoGenerated
  private Integer id;
  @Column(name = "name")
  private String name;
  @Column(name = "persion_num")
  private Integer persionNum;
  @Column(name = "status")
  private Integer status;// 状态0：空闲，1：使用中
  @Column(name = "floor")
  private Integer floor;// 楼层

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setPersionNum(Integer persionNum) {
    this.persionNum = persionNum;
  }

  public Integer getPersionNum() {
    return this.persionNum;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public Integer getStatus() {
    return this.status;
  }

  public Room() {}

  public Room(Integer id, String name, Integer persionNum, Integer status) {
    this.id = id;
    this.name = name;
    this.persionNum = persionNum;
    this.status = status;
  }

  public Integer getFloor() {
    return floor;
  }

  public void setFloor(Integer floor) {
    this.floor = floor;
  }

  public boolean isIdle() {
    return this.status.intValue() == 0;
  }
}
