package com.kevin.zuyu.model;

import java.math.BigDecimal;
import java.util.Date;

import com.kevin.orm.mapping.AutoGenerated;
import com.kevin.orm.mapping.Column;
import com.kevin.orm.mapping.PK_ID;
import com.kevin.orm.mapping.Table;

@Table(name = "service_order")
public class ServiceOrder {
  @PK_ID
  @AutoGenerated
  private int id;
  @Column(name = "order_id")
  private int orderId;
  @Column(name = "service_id")
  private int serviceId;
  @Column(name = "create_time")
  private Date createTime;
  @Column(name = "bjs_id")
  private int bjsId;
  @Column(name = "price")
  private BigDecimal price;

  private String serviceName;

  private BaoJianShi baoJianShi;

  public BaoJianShi getBaoJianShi() {
    return baoJianShi;
  }

  public void setBaoJianShi(BaoJianShi baoJianShi) {
    this.baoJianShi = baoJianShi;
  }

  public String getServiceName() {
    return serviceName;
  }

  public void setServiceName(String serviceName) {
    this.serviceName = serviceName;
  }

  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public int getOrderId() {
    return orderId;
  }

  public void setOrderId(int orderId) {
    this.orderId = orderId;
  }

  public int getServiceId() {
    return serviceId;
  }

  public void setServiceId(int serviceId) {
    this.serviceId = serviceId;
  }

  public Date getCreateTime() {
    return createTime;
  }

  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  public int getBjsId() {
    return bjsId;
  }

  public void setBjsId(int bjsId) {
    this.bjsId = bjsId;
  }

}
