package com.kevin.zuyu.model;

import java.math.BigDecimal;

import com.kevin.orm.mapping.AutoGenerated;
import com.kevin.orm.mapping.Column;
import com.kevin.orm.mapping.PK_ID;
import com.kevin.orm.mapping.Table;

@Table(name = "tao_can")
public class TaoCan implements java.io.Serializable {
  private static final long serialVersionUID = -5391202808698478311L;
  @PK_ID
  @AutoGenerated
  private Integer id;
  @Column(name = "name")
  private String name;
  @Column(name = "price")
  private BigDecimal price;
  @Column(name = "original_price")
  private BigDecimal originalPrice;
  @Column(name = "description")
  private String description;
  @Column(name = "status")
  private Integer status;
  @Column(name = "services_list")
  private String servicesList;

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public BigDecimal getPrice() {
    return this.price;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getDescription() {
    return this.description;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public Integer getStatus() {
    return this.status;
  }

  public void setServicesList(String servicesList) {
    this.servicesList = servicesList;
  }

  public String getServicesList() {
    return this.servicesList;
  }

  public BigDecimal getOriginalPrice() {
    return originalPrice;
  }

  public void setOriginalPrice(BigDecimal originalPrice) {
    this.originalPrice = originalPrice;
  }

  public TaoCan() {}

  public TaoCan(Integer id, String name, BigDecimal price, String description, Integer status, String servicesList) {
    this.id = id;
    this.name = name;
    this.price = price;
    this.description = description;
    this.status = status;
    this.servicesList = servicesList;
  }
}
